services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeteria_db
    ports:
      - "5433:5432" # host:container — DB_HOST=localhost en tu .env asume esto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
